spring:
  application:
    name: construction-site-safety
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/site_safety?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver