spring:
  application:
    name: construction-site-safety
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/site_safety?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver